name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif   

      - name: Put in a Defectdojo
        run: curl --location --request POST 'http://dd.dmytro.in.ua/api/v2/import-scan/' --header 'Authorization: Token b2a339909f50bb0b8c8dd033bbaa2d4efb1f82bc' --form 'engagement=10' --form 'verified=true' --form 'active=true' --form 'scan_type=SARIF' --form 'file=@tfsec.sarif'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif         