name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif   

      - name: Put in a Defectdojo
        run: |
          curl --location --request POST 'http://dd.dmytro.in.ua/api/v2/import-scan/' \
          --header 'Authorization: Token ${{ secrets.DD_TOKEN }}' \
          --form 'engagement=${{ secrets.DD_ENGAGEMENT}}' --form 'verified=true' --form 'active=true' \
          --form 'scan_type=SARIF' --form 'file=@./report.sarif'


      - name: Upload SARIF file
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: tfsec.sarif         